// <auto-generated />
using Farma.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Farma.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220804131121_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Farma.API.models.Remedio", b =>
                {
                    b.Property<int>("RemedioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("Preço")
                        .HasColumnType("REAL");

                    b.Property<string>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("RemedioId");

                    b.ToTable("Remedios");
                });
#pragma warning restore 612, 618
        }
    }
}
